#Database configuration
db_url: "127.0.0.1"
#dbPort = 7688 #Production environment
db_port: 7687 #Test environment
db_user: "neo4j"
#db_password: "NeO4J"
db_password: "lunar-parody-adrian-genesis-costume-1042"
