version: 1.0
pkg_directory: "/data/chenc/2023/PKG/pkg"
data_directory: "/data/chenc/2023/PKG/data"
archive_directory: "/data/chenc/2023/PKG/data/archive"
databases_directory: "/data/chenc/2023/PKG/data/databases"
experiments_directory: "/data/chenc/2023/PKG/data/experiments"
ontologies_directory: "/data/chenc/2023/PKG/data/ontologies"
users_directory: "/data/chenc/2023/PKG/data/users"
stats_directory: "/data/chenc/2023/PKG/data/stats"
downloads_directory: "/data/chenc/2023/PKG/data/downloads"
reports_directory: "/data/chenc/2023/PKG/data/reports"
tmp_directory: "/data/chenc/2023/PKG/data/tmp"
imports_directory: "/data/chenc/2023/PKG/data/imports"
imports_databases_directory: "/data/chenc/2023/PKG/data/imports/databases"
imports_experiments_directory: "/data/chenc/2023/PKG/data/imports/experiments"
imports_ontologies_directory: "/data/chenc/2023/PKG/data/imports/ontologies"
imports_users_directory: "/data/chenc/2023/PKG/data/imports/users"
imports_curated_directory: "/data/chenc/2023/PKG/data/imports/curated"
log_directory: "/data/chenc/2023/PKG/log"
report_manager_log: "/data/chenc/2023/PKG/pkg/config/report_manager_log.config"
graphdb_connector_log: "/data/chenc/2023/PKG/pkg/config/graphdb_connector_log.config"
graphdb_builder_log: "/data/chenc/2023/PKG/pkg/config/graphdb_builder_log.config"
analytics_factory_log: "/data/chenc/2023/PKG/pkg/config/analytics_factory_log.config"
